//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/angelica/RiderProjects/Documo/Documo/Documo.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IDocumoListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class DocumoBaseListener : IDocumoListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] DocumoParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] DocumoParser.StmtContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.placeholder"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlaceholder([NotNull] DocumoParser.PlaceholderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.placeholder"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlaceholder([NotNull] DocumoParser.PlaceholderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.repeatingSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRepeatingSection([NotNull] DocumoParser.RepeatingSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.repeatingSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRepeatingSection([NotNull] DocumoParser.RepeatingSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.startRepeatingSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStartRepeatingSection([NotNull] DocumoParser.StartRepeatingSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.startRepeatingSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStartRepeatingSection([NotNull] DocumoParser.StartRepeatingSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.endRepeatingSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndRepeatingSection([NotNull] DocumoParser.EndRepeatingSectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.endRepeatingSection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndRepeatingSection([NotNull] DocumoParser.EndRepeatingSectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject([NotNull] DocumoParser.ObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject([NotNull] DocumoParser.ObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.objectFieldAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectFieldAccess([NotNull] DocumoParser.ObjectFieldAccessContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.objectFieldAccess"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectFieldAccess([NotNull] DocumoParser.ObjectFieldAccessContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.objectName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectName([NotNull] DocumoParser.ObjectNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.objectName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectName([NotNull] DocumoParser.ObjectNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.objectField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectField([NotNull] DocumoParser.ObjectFieldContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.objectField"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectField([NotNull] DocumoParser.ObjectFieldContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
