//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/angelica/RiderProjects/Documo/Documo/Documo.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DocumoParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IDocumoListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStmt([NotNull] DocumoParser.StmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStmt([NotNull] DocumoParser.StmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.placeholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlaceholder([NotNull] DocumoParser.PlaceholderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.placeholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlaceholder([NotNull] DocumoParser.PlaceholderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.repeatingSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatingSection([NotNull] DocumoParser.RepeatingSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.repeatingSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatingSection([NotNull] DocumoParser.RepeatingSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.imagePlaceholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImagePlaceholder([NotNull] DocumoParser.ImagePlaceholderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.imagePlaceholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImagePlaceholder([NotNull] DocumoParser.ImagePlaceholderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.startRepeatingSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStartRepeatingSection([NotNull] DocumoParser.StartRepeatingSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.startRepeatingSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStartRepeatingSection([NotNull] DocumoParser.StartRepeatingSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.endRepeatingSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndRepeatingSection([NotNull] DocumoParser.EndRepeatingSectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.endRepeatingSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndRepeatingSection([NotNull] DocumoParser.EndRepeatingSectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] DocumoParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] DocumoParser.ObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.objectFieldAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectFieldAccess([NotNull] DocumoParser.ObjectFieldAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.objectFieldAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectFieldAccess([NotNull] DocumoParser.ObjectFieldAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.objectName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectName([NotNull] DocumoParser.ObjectNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.objectName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectName([NotNull] DocumoParser.ObjectNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DocumoParser.objectField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectField([NotNull] DocumoParser.ObjectFieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DocumoParser.objectField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectField([NotNull] DocumoParser.ObjectFieldContext context);
}
