//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /home/angelica/RiderProjects/Documo/Documo/Documo.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DocumoParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public interface IDocumoVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DocumoParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] DocumoParser.StmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DocumoParser.placeholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlaceholder([NotNull] DocumoParser.PlaceholderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DocumoParser.repeatingSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRepeatingSection([NotNull] DocumoParser.RepeatingSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DocumoParser.imagePlaceholder"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitImagePlaceholder([NotNull] DocumoParser.ImagePlaceholderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DocumoParser.startRepeatingSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStartRepeatingSection([NotNull] DocumoParser.StartRepeatingSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DocumoParser.endRepeatingSection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndRepeatingSection([NotNull] DocumoParser.EndRepeatingSectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DocumoParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObject([NotNull] DocumoParser.ObjectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DocumoParser.objectFieldAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectFieldAccess([NotNull] DocumoParser.ObjectFieldAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DocumoParser.objectName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectName([NotNull] DocumoParser.ObjectNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DocumoParser.objectField"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObjectField([NotNull] DocumoParser.ObjectFieldContext context);
}
